### ISSUE TITLE
設計したDBの作成

### ISSUE THREAD

**Issue by TakaraShinya** [tamashiro-syuta/Tech_Jam#14]
テーブル作成とサンプルデータ入れる。
DBダンプを共有して、同じDB構造のデータが共有できている状態が良い。

**Comment by nsmi** [comment]
scaffold実施予定
rails generate scaffold question user_name:string title:string content:text priority:integer
rails generate scaffold answer user_name:string content:text answers.question_id:integer

answers.question_id:integer

answers. は必要なのか確認

**Comment by nsmi** [comment]
rails generate scaffold question user_name:string title:string content:text priority:integer
rails generate scaffold answer user_name:string content:text question_id:integer
変更など
